name: Build Project with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 22 (Temurin distribution)
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'  # Official OpenJDK distribution

      # Step 3: Set up Maven 3.8.2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      # Step 4: Set up Chrome browser for tests
      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@v1

      # Step 5: Set up Firefox browser for tests
      - name: Set up Firefox browser
        uses: browser-actions/setup-firefox@v1

      # Step 6: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 7: Run the tests (ensure the test is configured to use Chrome or Firefox)
      - name: Run Tests
        run: mvn test
