name: Build Project with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use macos-latest or windows-latest, depending on your requirement

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 22 (Temurin distribution)
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'  # Official OpenJDK distribution

      # Step 3: Set up Maven 3.8.2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      # Step 4: Setup Edge using browser-actions
      - uses: browser-actions/setup-edge@v1

      # Step 5: Print the Edge version (cross-platform)
      - name: Print Edge version
        run: |
          msedge --version || echo "Edge not found on this platform."

      # Step 6: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install
