name: Build Project with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 22 (Temurin distribution)
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'  # Official OpenJDK distribution

      # Step 3: Set up Maven 3.8.2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      # Step 4: Install Chromium (Chrome browser) and WebDriver
      - name: Install Chromium and ChromeDriver
        run: |
          # Install Chromium browser
          sudo apt-get update
          sudo apt-get install -y chromium-browser

          # Install ChromeDriver
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Step 5: Install GeckoDriver (for Firefox)
      - name: Install GeckoDriver (Firefox)
        run: |
          # Download and install GeckoDriver for Firefox
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      # Step 6: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install
