name: Cypress CI Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up JDK 22 with Zulu
      uses: actions/setup-java@v3
      with:
        java-version: '22'  # Set up JDK 22
        distribution: 'zulu'  # Use the Zulu JDK distribution (supports JDK 22)
        java-package: jdk  # Ensure the JDK is installed

    - name: Install Maven manually
      run: |
        # Install Maven 3.9.1
        wget https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
        tar -xvf apache-maven-3.9.1-bin.tar.gz
        sudo mv apache-maven-3.9.1 /opt/maven
        sudo ln -s /opt/maven/bin/mvn /usr/local/bin/mvn
        mvn --version  # Check Maven version

    - name: Install the latest ChromeDriver
      run: |
        # Install the latest ChromeDriver that matches the installed version of Chrome
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        LATEST_CHROMEDRIVER=$(curl -sSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        wget "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d /usr/local/bin/

    - name: Install the latest EdgeDriver
      run: |
        # Install the latest EdgeDriver that matches the installed version of Edge
        EDGE_VERSION=$(microsoft-edge --version | awk '{print $3}')
        LATEST_EDGEDRIVER=$(curl -sSL "https://msedgedriver.azureedge.net/LATEST_RELEASE_${EDGE_VERSION}")
        wget "https://msedgedriver.azureedge.net/${LATEST_EDGEDRIVER}/edgedriver_linux64.zip"
        unzip edgedriver_linux64.zip -d /usr/local/bin/

    - name: Install dependencies and build project
      run: |
        mvn clean install  # Install dependencies and build the project

    - name: Install Cypress
      uses: cypress-io/github-action@v4  # Install and set up Cypress

    - name: Run Cypress tests
      run: |
        npx cypress run --headless  # Run Cypress tests in headless mode
