name: Build Project with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'

      # Step 3: Install Maven
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          maven-version: '3.8.1'

      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: |
          mvn clean install

      # Optionally: Upload build artifacts if needed
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build-artifacts
      #     path: target/*.jar
