name: Cypress CI Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up JDK 22 with Zulu
      uses: actions/setup-java@v3
      with:
        java-version: '22'  # Set up JDK 22
        distribution: 'zulu'  # Use the Zulu JDK distribution (supports JDK 22)
        java-package: jdk  # Ensure the JDK is installed

    - name: Install Maven manually
      run: |
        # Install Maven 3.9.1
        wget https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
        tar -xvf apache-maven-3.9.1-bin.tar.gz
        sudo mv apache-maven-3.9.1 /opt/maven
        sudo ln -s /opt/maven/bin/mvn /usr/local/bin/mvn
        mvn --version  # Check Maven version

    - name: Install ChromeDriver
      uses: googlechrome/setup-chromedriver@v2  # Install ChromeDriver using GitHub's official action

    - name: Install EdgeDriver
      uses: microsoft/setup-msedge-driver@v1  # Install EdgeDriver using GitHub's official action

    - name: Install GeckoDriver (Firefox)
      uses: mozilla/setup-geckodriver@v2  # Install GeckoDriver for Firefox using GitHub's official action

    - name: Install dependencies and build project
      run: |
        mvn clean install  # Install dependencies and build the project

    - name: Install Cypress
      uses: cypress-io/github-action@v4  # Install and set up Cypress

    - name: Run Cypress tests
      run: |
        npx cypress run --headless  # Run Cypress tests in headless mode
