name: Cypress CI Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '22'  # Set up JDK 22 (or whichever version you're using)
        distribution: 'adoptopenjdk'  # Specify the distribution (e.g., adoptopenjdk, zulu, oracle)
        cache: maven  # Cache Maven dependencies to speed up builds

    - name: Install dependencies and build project
      run: |
        mvn clean install  # Install dependencies and build the project

    - name: Install Cypress
      uses: cypress-io/github-action@v4  # Install and set up Cypress

    - name: Run Cypress tests
      run: |
        npx cypress run --headless  # Run Cypress tests in headless mode
