name: Build Project with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 22 (Temurin distribution)
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'  # Official OpenJDK distribution

      # Step 3: Set up Maven 3.8.2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      # Step 4: Setup Chrome using browser-actions
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      # Step 5: Check Chrome version
      - name: Check Chrome version
        run: chrome --version

      # Step 6: Setup Firefox using browser-actions
      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1

      # Step 7: Check Firefox version
      - name: Check Firefox version
        run: firefox --version

      # Step 8: Setup Edge using browser-actions (for Windows-based environments, adjust if needed)
      - name: Set up Edge
        uses: browser-actions/setup-edge@v1
        if: runner.os == 'Windows'

      # Step 9: Check Edge version
      - name: Check Edge version
        if: runner.os == 'Windows'
        run: |
          (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion

      # Step 10: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install
